volumePermissions:  
  enabled: true
tls:
  enabled: true
  certificatesSecret: postgresql-tls-secret
  certFilename: "tls.crt"
  certKeyFilename: "tls.key"
auth:
  existingSecret: postgresql-admin-password
primary:
  service:
    annotations:
      service.beta.openshift.io/serving-cert-secret-name: postgresql-tls-secret
