# permissions for end users to edit artifactorysecretengineconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: artifactorysecretengineconfig-editor-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - artifactorysecretengineconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - artifactorysecretengineconfigs/status
  verbs:
  - get
