# permissions for end users to view artifactorysecretengineroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: artifactorysecretenginerole-viewer-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - artifactorysecretengineroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - artifactorysecretengineroles/status
  verbs:
  - get
