# permissions for end users to view authenginemounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: authenginemount-viewer-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - authenginemounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - authenginemounts/status
  verbs:
  - get
