# permissions for end users to edit kubernetesauthengineconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetesauthengineconfig-editor-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - kubernetesauthengineconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - kubernetesauthengineconfigs/status
  verbs:
  - get
