# permissions for end users to view kubernetesauthengineroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetesauthenginerole-viewer-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - kubernetesauthengineroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - kubernetesauthengineroles/status
  verbs:
  - get
