# permissions for end users to edit kubernetesauthengineroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetesauthenginerole-editor-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - kubernetesauthengineroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - kubernetesauthengineroles/status
  verbs:
  - get
